### ISSUE TITLE
API활용 중 CORS 오류!!

### ISSUE THREAD

**Issue by jobumjin** [jobumjin/Web-FrontEnd-Miniproject#1]
공공데이터 API를 Java Script에 연결하여 사용하려 했지만 CORS오류가 반복해서 발생하는 현상이 일어났다!! 해결방법은.. 뭐가있을까?

**Comment by MaryYoungae** [comment]
https://perlpark.github.io/articles/2019-09-25-TIL-CORS/ 
참고하세용

**Comment by dongkyuu** [comment]
어제 찾아봤어요 ㅎㅎ
https://beomsoo.me/issue/Issue-5/

**Comment by jobumjin** [comment]
좋아요 함께 해결봅시다ㅋㅋㅋ

**Comment by MaryYoungae** [comment]
자바스크립트로하면 발생하는 이슈라고 하네요 추후에 node.js 배우고 고쳐 봅시당

**Comment by jobumjin** [comment]
앞으로 Issues는 Template 활용해서 쓰는게 좋다고 합니다!! 나중엔 그렇게 적용해보아요~
![image](https://user-images.githubusercontent.com/71051838/155673029-3a2b9d37-d0fa-49fe-af21-cb575932ac21.png)
